# -*- coding: utf-8 -*-
"""НКС_ЛР3_Вохминова_410.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1xhIZmrDJDv6DWiEwTwSVkhCG0Xi1i6gi
"""

# Установка зависимостей
!pip install -q transformers torch accelerate

print("Библиотеки установлены")

# путь к модели
MODEL_PATH = "my_model"


# Проверка GPU
import torch

if torch.cuda.is_available():
    device = "cuda"
    print(f"GPU доступен: {torch.cuda.get_device_name(0)}")
else:
    device = "cpu"
    print("GPU не найден, работаем на CPU (будет медленно)")

#Загрузка модели и токенизатора
from transformers import AutoModelForCausalLM, AutoTokenizer

print("\n Загрузка модели... Это может занять несколько минут")

tokenizer = AutoTokenizer.from_pretrained(MODEL_PATH, use_fast=True)

model = AutoModelForCausalLM.from_pretrained(
    MODEL_PATH,
    torch_dtype=torch.float16 if device == "cuda" else torch.float32,
    device_map="auto",
    low_cpu_mem_usage=True
)

# Настройка pad_token
if tokenizer.pad_token is None:
    tokenizer.pad_token = tokenizer.eos_token

model.eval() #режим интерференса
print("Модель успешно загружена!")

# Функция для генерации ответа
def get_response(user_input, max_new_tokens=300):
    """Генерация ответа модели"""
    prompt = f"Вопрос: {user_input}\n\nОтвет:"
    inputs = tokenizer(prompt, return_tensors="pt").to(device)

    with torch.no_grad():
        outputs = model.generate(
            **inputs,
            max_new_tokens=max_new_tokens,
            do_sample=False,
            repetition_penalty=1.15,
            no_repeat_ngram_size=3,
            pad_token_id=tokenizer.eos_token_id,
            eos_token_id=tokenizer.eos_token_id,
        )

    response = tokenizer.decode(outputs[0], skip_special_tokens=True)
    answer = response[len(prompt):].strip() if response.startswith(prompt) else response.strip()
    return answer

# Запуск консольного чата
print("\n" + "="*60)
print("КОНСОЛЬНЫЙ ЧАТ С ДООБУЧЕННОЙ МОДЕЛЬЮ")
print("="*60)
print("Модель готова к диалогу!")
print("Для выхода введите: exit, quit или выход")
print("="*60)

while True:
    user_input = input("\nВы: ").strip()

    if user_input.lower() in ["exit", "quit", "выход"]:
        print("\nЗавершение работы. До свидания!")
        break

    if not user_input:
        print("Пожалуйста, введите текст")
        continue

    print("\nБот: ", end="", flush=True)
    try:
        answer = get_response(user_input)
        print(answer)
    except Exception as e:
        print(f"\nОшибка: {e}")
        print("Попробуйте еще раз")

    print("-"*60)

"""Установка и подключение веб-интерфейса"""

!pip install -q fastapi uvicorn nest-asyncio

print("Библиотеки для веб-интерфейса установлены")

# веб чат (с загрузкой модели)
# 1. Останавливаем всё на порту 8000
!fuser -k 8000/tcp 2>/dev/null
import time
time.sleep(2)

# 2. Убеждаемся, что модель загружена (если нет - загружаем)
try:
    # Проверяем, существует ли модель
    model
    print("Модель уже загружена")
except NameError:
    print(" Модель не найдена, загружаем...")
    # Здесь ваш код загрузки модели
    from transformers import AutoModelForCausalLM, AutoTokenizer
    import torch

    MODEL_PATH = "my_model"

    device = "cuda" if torch.cuda.is_available() else "cpu"
    tokenizer = AutoTokenizer.from_pretrained(MODEL_PATH, use_fast=True)
    model = AutoModelForCausalLM.from_pretrained(
        MODEL_PATH,
        torch_dtype=torch.float16 if device == "cuda" else torch.float32,
        device_map="auto"
    )
    if tokenizer.pad_token is None:
        tokenizer.pad_token = tokenizer.eos_token
    model.eval()
    print(f"Модель загружена на {device}")

# 3. Определяем функцию get_response
def get_response(user_input, max_new_tokens=300):
    """Генерация ответа модели"""
    prompt = f"Вопрос: {user_input}\n\nОтвет:"
    inputs = tokenizer(prompt, return_tensors="pt").to(device)

    with torch.no_grad():
        outputs = model.generate(
            **inputs,
            max_new_tokens=max_new_tokens,
            do_sample=False,
            repetition_penalty=1.15,
            no_repeat_ngram_size=3,
            pad_token_id=tokenizer.eos_token_id,
            eos_token_id=tokenizer.eos_token_id,
        )

    response = tokenizer.decode(outputs[0], skip_special_tokens=True)
    answer = response[len(prompt):].strip() if response.startswith(prompt) else response.strip()
    return answer

print(" Функция get_response определена")

# 4. Создаем FastAPI приложение
from fastapi import FastAPI
from fastapi.responses import HTMLResponse
from pydantic import BaseModel
from typing import List

# Простая HTML страница
SIMPLE_HTML = """
<!DOCTYPE html>
<html>
<head>
    <title>LLM Security Chat</title>
    <meta charset="UTF-8">
    <style>
        body { font-family: Arial; max-width: 800px; margin: 50px auto; padding: 20px; }
        #chat { height: 400px; overflow-y: auto; border: 1px solid #ccc; padding: 10px; margin-bottom: 20px; background: #f9f9f9; border-radius: 10px; }
        .user { color: #0066cc; font-weight: bold; }
        .bot { color: #009900; font-weight: bold; }
        textarea { width: 100%; height: 80px; margin-bottom: 10px; padding: 10px; border: 1px solid #ccc; border-radius: 5px; }
        button { padding: 10px 20px; background: #007bff; color: white; border: none; cursor: pointer; border-radius: 5px; }
        button:hover { background: #0056b3; }
        .loading { color: #ff9900; font-style: italic; }
        h1 { color: #333; }
    </style>
</head>
<body>
    <h1>🤖 Консультант по безопасности LLM</h1>
    <p><strong>Тема:</strong> Безопасность больших языковых моделей</p>
    <div id="chat">
        <div><span class="bot">Бот:</span> Здравствуйте! Задайте вопрос по безопасности LLM.</div>
    </div>
    <textarea id="message" placeholder="Введите вопрос..."></textarea>
    <button onclick="sendMessage()">Отправить</button>
    <div id="loading" style="display:none;" class="loading">⏳ Модель думает...</div>

    <script>
        async function sendMessage() {
            const msg = document.getElementById('message').value;
            if (!msg) return;

            const chat = document.getElementById('chat');
            chat.innerHTML += `<div><span class="user">Вы:</span> ${msg}</div>`;
            document.getElementById('message').value = '';
            chat.scrollTop = chat.scrollHeight;

            document.getElementById('loading').style.display = 'block';

            try {
                const response = await fetch('/chat', {
                    method: 'POST',
                    headers: {'Content-Type': 'application/json'},
                    body: JSON.stringify({message: msg, history: []})
                });
                const data = await response.json();
                chat.innerHTML += `<div><span class="bot">Бот:</span> ${data.response}</div>`;
            } catch (error) {
                chat.innerHTML += `<div><span class="bot">Бот:</span> Ошибка: ${error.message}</div>`;
            }

            document.getElementById('loading').style.display = 'none';
            chat.scrollTop = chat.scrollHeight;
        }
    </script>
</body>
</html>
"""

app = FastAPI()

@app.get("/")
async def root():
    return HTMLResponse(SIMPLE_HTML)

@app.post("/chat")
async def chat(request: dict):
    message = request.get('message', '')
    if not message:
        return {"response": "Пожалуйста, введите вопрос"}
    try:
        answer = get_response(message, max_new_tokens=200)
        return {"response": answer}
    except Exception as e:
        return {"response": f"Ошибка: {str(e)}"}

print("FastAPI приложение создано")

# 5. Запускаем сервер
import threading
import uvicorn
import nest_asyncio
from google.colab.output import eval_js

nest_asyncio.apply()

def run():
    uvicorn.run(app, host="0.0.0.0", port=8000, log_level="error")

thread = threading.Thread(target=run, daemon=True)
thread.start()

time.sleep(3)

# 6. Показываем ссылку
try:
    url = eval_js("google.colab.kernel.proxyPort(8000)")
    print("\n" + "="*60)
    print("ВЕБ-ЧАТ ЗАПУЩЕН!")
    print("="*60)

    # Открываем прямо в Colab
    from IPython.display import IFrame, display
    display(IFrame(url, width=900, height=600))

except Exception as e:
    print(f" Ошибка: {e}")
    print("\nПопробуйте открыть вручную:")
    print("   https://localhost:8000")